# Generated by Django 5.0.2 on 2024-02-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharemodel',
            name='current_price',
            field=models.CharField(max_length=50),
        ),
    ]
