# Generated by Django 5.0.2 on 2024-03-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0002_alter_sharemodel_current_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharemodel',
            name='logo',
            field=models.CharField(default='', max_length=250),
        ),
    ]
