# Generated by Django 5.0.2 on 2024-03-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0003_sharemodel_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progres_type', models.CharField(choices=[('t_sale', 't_sale'), ('t_1_sale', 't_1_sale'), ('t_2_sale', 't_2_sale'), ('buy', 'buy')], default='buy', max_length=10)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='shareownershipmodel',
            name='piece',
        ),
        migrations.RemoveField(
            model_name='shareownershipmodel',
            name='purchase_price',
        ),
        migrations.RemoveField(
            model_name='shareownershipmodel',
            name='sold',
        ),
        migrations.AddField(
            model_name='shareownershipmodel',
            name='slots',
            field=models.ManyToManyField(to='share.slotmodel'),
        ),
    ]
