# Generated by Django 5.0.2 on 2024-03-06 11:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0004_slotmodel_remove_shareownershipmodel_piece_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slotmodel',
            options={'ordering': ('action_time',)},
        ),
        migrations.AddField(
            model_name='slotmodel',
            name='action_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
