# Generated by Django 5.0.2 on 2024-03-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0006_publicofferingmodel_sharemodel_previous_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sharemodel',
            options={'ordering': ('code',)},
        ),
        migrations.AlterField(
            model_name='slotmodel',
            name='action_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
