# Generated by Django 5.0.2 on 2024-03-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0008_alter_slotmodel_action_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotmodel',
            name='action_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
